name: Fetch Quests
on:
  workflow_dispatch

jobs:
  fetch_quests:
    runs-on: ubuntu-latest
    name: Fetch Quest Data
    permissions:
      contents: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      
      - run: npm install
      
      - name: Get data from DDO wiki
        id: fetchQuests
        uses: ./fetchQuests
        with:
          proxy: ${{ secrets.Proxy }}
      
      - uses: EndBug/add-and-commit@v9.1.0
        with:
          add: 'quests.json'
          author_name: Argavyon
          author_email: 75849479+Argavyon@users.noreply.github.com
          default_author: github_actor
          fetch: --force
          message: Fetched quest data from wiki
          push: true
